import { GoogleGenAI } from "@google/genai";
import { GarmentSelection } from "../types";

// Ensure process.env.API_KEY is available during build/runtime
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

// Helper to convert base64 to raw data for the SDK if needed, 
// though inlineData usually expects the base64 string directly.
// We strip the data:image/xyz;base64, prefix if present.
const cleanBase64 = (b64: string) => b64.replace(/^data:image\/\w+;base64,/, "");

export const generateTryOn = async (
  modelImage: string,
  garments: GarmentSelection,
  category: string
): Promise<string> => {
  const model = "gemini-2.5-flash-image";

  // Start building the parts array with the model image
  const parts: any[] = [
    {
      inlineData: {
        mimeType: "image/jpeg",
        data: cleanBase64(modelImage),
      },
    }
  ];

  let promptDescription = "Image 1 is the fashion model (person). ";
  let imageIndex = 2; // Image 1 is model, next is 2

  // Add garments to parts and prompt description based on what was uploaded
  if (garments.upper) {
    parts.push({
      inlineData: { mimeType: "image/jpeg", data: cleanBase64(garments.upper) }
    });
    promptDescription += `Image ${imageIndex} is the upper body garment (top/shirt). `;
    imageIndex++;
  }

  if (garments.lower) {
    parts.push({
      inlineData: { mimeType: "image/jpeg", data: cleanBase64(garments.lower) }
    });
    promptDescription += `Image ${imageIndex} is the lower body garment (pants/skirt). `;
    imageIndex++;
  }

  if (garments.accessory) {
    parts.push({
      inlineData: { mimeType: "image/jpeg", data: cleanBase64(garments.accessory) }
    });
    promptDescription += `Image ${imageIndex} is a fashion accessory (bag/jewelry/hat). `;
    imageIndex++;
  }

  const prompt = `
    You are a professional fashion editor.
    ${promptDescription}
    
    Task: Generate a photorealistic image of the person from Image 1 wearing ALL the provided fashion items defined above.
    
    Requirements:
    - Retain the model's identity, pose, and body shape as closely as possible from Image 1.
    - If a specific garment slot (e.g., pants) was NOT provided, keep the model's original clothing for that area.
    - If a garment WAS provided, replace the model's original clothing with the new item naturally.
    - Ensure lighting, shadows, and fabric textures match high-end fashion photography.
    - The result must look like a cohesive outfit.
  `;

  parts.push({ text: prompt });

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: parts,
      },
    });

    const responseParts = response.candidates?.[0]?.content?.parts;
    if (responseParts) {
      for (const part of responseParts) {
        if (part.inlineData) {
          return `data:image/jpeg;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the AI.");
  } catch (error) {
    console.error("TryOn Error:", error);
    throw error;
  }
};

export const generateBackgroundChange = async (
  currentImage: string,
  backgroundPrompt: string
): Promise<string> => {
  const model = "gemini-2.5-flash-image";

  const prompt = `
    Image 1 is a fashion model.
    Task: Change the background of this image to match this description: "${backgroundPrompt}".
    
    Requirements:
    - KEEP the model and their clothing EXACTLY as they are. Do not change the person or the outfit.
    - Replace only the environment/background.
    - Ensure the lighting on the model looks integrated with the new background.
    - Photorealistic result.
  `;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: "image/jpeg",
              data: cleanBase64(currentImage),
            },
          },
          { text: prompt },
        ],
      },
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
      for (const part of parts) {
        if (part.inlineData) {
          return `data:image/jpeg;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No background image generated.");
  } catch (error) {
    console.error("Background Change Error:", error);
    throw error;
  }
};